### PR TITLE
Fixes autoplay not working correctly

### LINKED ISSUE #16: autoplay not working
Loving the work done here!

I can't seem to get `autoplay` to work on my end though. Should this be added alongside `control`?

### PR DESCRIPTION
**Pull request by evoactivity**
Resolves #16

### CODE REVIEW

**Comment by luwes** [comment]
@evoactivity thanks for the work!

I believe this bug might be related to the older pkg https://github.com/muxinc/custom-video-element

the plan is to add the new https://github.com/muxinc/custom-media-element here.
we should try that first to see if it fixes this bug

**Comment by evoactivity** [comment]
I am planning on trying that tonight. Though I think a similar solution will still be necessary, I found autoplay to be inconsistent between refreshes when I wrote a my mpegts element and resorted to a similar strategy of calling play manually on load.

**Comment by evoactivity** [comment]
@luwes Would moving the repo to vite and typescript potentially be a blocker for you guys or would that be something you welcome?

**Comment by evoactivity** [comment]
Updating to use `custom-media-element` seems to have resolved the issue in my case, without this change, so I'm going to close it.

**Comment by luwes** [comment]
yes, I think we want to hold off on Typescript for this size of project and Vite as well.

if we would replace bundler it would probably be `esbuild` but we might do away with bundling like in my fork 
https://github.com/luwes/hls-video-element

**Comment by evoactivity** [comment]
Oh cool, your fork does a lot of stuff I was considering adding in my fork so I'll hold off on anymore PR's here until there is time to merge your work.

**Pull request closed without merging**
